name: LoginReward
version: '${project.version}'
main: net.hotamachisubaru.loginreward.LoginReward
api-version: '1.21'
load: STARTUP
depend:
  - "Vault"
commands:
  loginreward:
    description: "ログインボーナスのコマンド"
    usage: "/loginreward"
  setdate:
    description: "強制的に日付を変更するコマンド"
    usage: "/setdate"
    permission: "loginreward.setdate"
    default: op
permissions:
  loginreward.setdate:
    description: "強制的に日付を変更するコマンド"
    default: op