name: LoginReward
version: '${project.version}'
main: org.nanndeyanenw.loginreward.LoginReward
api-version: '1.20'
load: STARTUP
depend:
  - "Vault"
commands:
  loginreward:
    description: "ログインボーナスのコマンド"
    usage: "/loginreward"
  debugdate:
    description: "デバッグ用の日付表示コマンド"
    usage: "/debugdate"
    permission: "loginreward.debugdate"
    default: op
permissions:
  loginreward.debugdate:
    description: "デバッグ日付コマンドを実行する権限"
    default: op
